### PR TITLE
Fix for new NTL versions

### LINKED ISSUE #10: Tests fail with conda-forge
I'd like to package this for conda-forge. However, some checks are failing: https://github.com/conda-forge/staged-recipes/pull/8959#issuecomment-515934497

These also fail for me locally. Am I doing something wrong? Or are they supposed to fail?

### PR DESCRIPTION
**Pull request by isuruf**
cc @saraedum 

Fixes https://github.com/latte-int/latte/issues/10

### CODE REVIEW

**Comment by saraedum** [comment]
Wow, thanks @isuruf for figuring this one out.

File: code/latte/rational.cpp [hunk 1]
```diff
@@ -200,6 +200,11 @@ void RationalNTL::canonicalize()
 		denominator *= -1;
 		numerator *= -1;
 	}//make denominator positive.
+	else if (denominator == 0)
```
Comment (isuruf) [inline code/latte/rational.cpp:203]: This case happens when `denominator = 0` and `numerator = 0`. With older NTL versions, this method returned `0`, with newer ones an error occured.

**Comment by mkoeppe** [comment]
@isuruf Thanks very much!
